[package]
name = "ips4o"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = { version = "0.8", features = ["small_rng"] }

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "bench"
harness = false

[profile.release]
